name: aadc
channels:
  - defaults
dependencies:
  - python=3.6
  - testpath<0.4            # fix pip (https://github.com/conda-forge/testpath-feedstock/issues/7)
  - setuptools<39.1         # fix sounddevice dependencies
  - numpy>=1.13.3,<=1.14.5  # fix sounddevice dependencies
  - pyzmq=17.1.2
  - scikit-learn=0.19.1
  - scipy=1.1
  - lxml=4.2
  - cython=0.28
  - keras=2.2
  - jupyterlab
  - matplotlib
  - pip:
    - PyHamcrest>=1.9
    - sounddevice>=0.3
